title: Mega Big News
author:
  name: Mega Big News
  email: megabignews@gmail.com
description: |
  Newsing all over you.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
minima:
  skin: auto
