title: "LoveBites: Advice for the Paranormal Lovelorn"
author:
  name: " LB"
  email: paralovebites@gmail.com
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
  - disclaimer.md
minima:
  skin: auto
